[forest]
trees = ["trees" ]  # The directories in which your trees are stored
assets = ["assets"] # The directories in which your assets are stored
theme = "base-theme"     # The directory in which your theme is stored
host = "CHANGEME"
url = "http://localhost:8080/"

[renderer]
home = "index"
